## 1. Import thư viện và nạp dữ liệu vào notebook
+ file data này không sài dấu "," mà sài dấu cách

In [24]:
# Cài đặt các thư viện EDA tự động trên Google Colab
!pip install dtale autoviz sweetviz -q
!pip install ydata-profiling "kaleido==0.2.1" -q

In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
import pandas as pd
import dtale
from autoviz.AutoViz_Class import AutoViz_Class
import os
import sweetviz as sv
from ydata_profiling import ProfileReport
marketing_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data/marketing_campaign.csv", sep='\t')
marketing_data = marketing_data[['ID','Year_Birth', 'Education', 'Marital_Status','Income','Kidhome', 'Teenhome','Dt_Customer', 'Recency','NumStorePurchases', 'NumWebVisitsMonth']]

## 2. Loại bỏ dữ liệu trùng lặp
+ axis = 0 là dòng, axis = 1 là cột.
+ 2 lệnh đầu là bắt buộc, tất yếu sài để kiểm tra dữ liệu và loại bỏ các dòng bị trùng lập.
+ 2 lệnh cuối là xóa dòng, cột. chúng xuất hiện trong bài với mục đích là dạy ta cách xóa dòng, cột.
+ vì nếu xóa thật thì phải **gán đè biến** hoặc thêm tham số **inplace=true** (xóa thật ở đây là xóa ở dữ liệu gốc)
+ xóa dòng thì dùng để xóa các dữ liệu rác, lỗi,... vì dữ liệu thực tế rất bẩn
+ xóa cột thì dùng khi cột đó không có giá trị phân tích, dư thừa. xóa để nó sạch, trống, dễ nhìn.

In [27]:
marketing_data.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5

In [28]:
print(marketing_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 2240 non-null   int64
 1   Year_Birth         2240 non-null   int64
 2   Education          2240 non-null   object
 3   Marital_Status     2240 non-null   object
 4   Income             2216 non-null   float64
 5   Kidhome            2240 non-null   int64
 6   Teenhome           2240 non-null   int64
 7   Dt_Customer        2240 non-null   object
 8   Recency            2240 non-null   int64
 9   NumStorePurchases  2240 non-null   int64
 10  NumWebVisitsMonth  2240 non-null   int64
dtypes: float64(1), int64(7), object(3)
memory usage: 192.6+ KB
None

### 2.1. Loại bỏ các dòng bị trùng lặp hoàn toàn trên tất cả các cột trong tập dữ liệu:

In [29]:
marketing_data_duplicate = marketing_data.drop_duplicates()

### 2.2. Xóa một dòng cụ thể tại chỉ số (index) là 1:

In [30]:
marketing_data.drop(labels=[1], axis=0)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5
5,7446,1967,Master,Together,62513.0,0,1,09-09-2013,16,10,6
...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,4,5
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,5,7
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,13,6
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,10,3
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,4,7

### 2.3. Xóa một cột đơn lẻ (ở đây là cột Year_Birth):

In [31]:
marketing_data.drop(labels=['Year_Birth'], axis=1)

,ID,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,PhD,Married,58293.0,1,0,19-01-2014,94,6,5
...,...,...,...,...,...,...,...,...,...,...
2235,10870,Graduation,Married,61223.0,0,1,13-06-2013,46,4,5
2236,4001,PhD,Together,64014.0,2,1,10-06-2014,56,5,7
2237,7270,Graduation,Divorced,56981.0,0,0,25-01-2014,91,13,6
2238,8235,Master,Together,69245.0,0,1,24-01-2014,8,10,3
2239,9405,PhD,Married,52869.0,1,1,15-10-2012,40,4,7

## 3. Thay thế dữ liệu và thay đổi định dạng của dữ liệu
+ Chuyển đổi dữ liệu định dạng số (0, 1, 2) của cột Teenhome sang dạng chữ dễ đọc, dễ hiểu hơn.
+ làm Khi số lượng nhóm giá trị ít (ví dụ: 0, 1, 2) và ta muốn gom nhóm lại thành các trạng thái phân loại cụ thể (kém/yếu/trungbinh/tốt,...)
+ còn điền khuyết giá trị phải làm chứ không là làm lệch dữ liệu, hệ thống báo lỗi.
+ đổi float -> int Khi phát hiện kiểu dữ liệu bị Pandas nhận diện sai lúc đọc file

### 3.1. Thay thế các giá trị trong cột Teenhome thành 'has teen' (có con tuổi teen) và 'has no teen' (không có)

In [32]:
marketing_data['Teenhome_replaced'] = marketing_data['Teenhome'].replace([0,1,2],['has no teen','has teen','has teen'])

### 3.2. Điền các giá trị bị khuyết (NaN/NAs) trong cột Income bằng số 0

In [33]:
marketing_data['Income'] = marketing_data['Income'].fillna(0)

### 3.3. Thay đổi kiểu dữ liệu của cột Income từ số thực (float) sang số nguyên (int)

In [34]:
marketing_data['Income_changed'] = marketing_data['Income'].astype(int)

## 4. Xử lý dữ liệu thiếu

### 4.1. Kiểm tra các giá trị bị thiếu (khuyết) bằng cách kết hợp hai phương thức isnull và sum

In [35]:

marketing_data.isnull().sum()

ID                   0
Year_Birth           0
Education            0
Marital_Status       0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
Recency              0
NumStorePurchases    0
NumWebVisitsMonth    0
Teenhome_replaced    0
Income_changed       0
dtype: int64

### 4.2. Loại bỏ các giá trị bị thiếu bằng phương thức dropna

In [36]:

marketing_data_withoutna = marketing_data.dropna(how = 'any')
marketing_data_withoutna.shape

(2240, 13)

## 5. Công Cụ Hỗ TroTrợ EDA tự động

In [37]:
# Create an Automated EDA report using the ProfileReport class in the ydata_profiling library. Use the to_file method to output the report to an HTML file

# Tự động tạo thư mục Reports nếu chưa có
os.makedirs("Reports", exist_ok=True)
profile = ProfileReport(marketing_data)
# Lưu trực tiếp vào Google Drive
profile.to_file("/content/drive/MyDrive/profile_output.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/13 [00:00<?, ?it/s]
 23%|██▎       | 3/13 [00:00<00:00, 22.14it/s]
 54%|█████▍    | 7/13 [00:00<00:00, 28.27it/s]
100%|██████████| 13/13 [00:00<00:00, 28.06it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [38]:
dtale.show(marketing_data).open_browser()

In [39]:
report = sv.analyze(marketing_data)

# Xuất ra file HTML
# Lưu trực tiếp vào Google Drive
report.show_html("/content/drive/MyDrive/sweetviz_report.html")

                                             |          | [  0%]   00:00 -> (? left)

Report /content/drive/MyDrive/sweetviz_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [40]:
dfte = AV.AutoViz(
    filename="",
    sep='\t',
    depVar='',
    dfte=marketing_data,
    save_plot_dir="/content/drive/MyDrive/AutoViz_Plots" # Lưu toàn bộ biểu đồ vào Drive
)

Shape of your Data Set loaded: (2240, 13)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  1
    Number of Integer-Categorical Columns =  7
    Number of String-Categorical Columns =  2
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  1
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  1
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  0
    13 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['ID']
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular

Could not draw wordcloud plot for Dt_Customer.
Looks like you are missing some required data for this feature.

To download the necessary data, simply run

    python -m textblob.download_corpora

or use the NLTK downloader to download the missing data: http://nltk.org/data.html
If this doesn't fix the problem, file an issue at https://github.com/sloria/TextBlob/issues.

All Plots done
Time to run AutoViz = 2 seconds

 ###################### AUTO VISUALIZATION Completed ########################